-- -------------------------------------------------------------------------------------------------
-- ---------------------- Choosing goalkeeper:----------------------------------------------------------
-- -------------------------------------------------------------------------------------------------
WITH minutes_played_condition AS (
    -- CTE Query to get all players with at least 450 minutes played
    SELECT  -- columns to get after join (3)
        m.id_player,
        m.player_name,
        m.position,
        k.minutes_played
    FROM ucl21_22.main AS m -- Table 1 to join (1)
    JOIN ucl21_22.key_stats AS k ON m.id_player = k.id_player -- Table 2 to join (inner) (2)
    WHERE k.minutes_played > 300
    -- in WHERE is defined the condition minutes played over the average, using subqueries (4)
),
goalkeeper_condition AS (
    -- CTE Query to get all players with no red cards and up to 3 yellow cards
    SELECT -- columns to get after join (10)
        mpc.player_name,
        mpc.position,
        mpc.minutes_played,
        disc.red,
        disc.yellow,
        gk.conceded,
        gk.saved
	FROM minutes_played_condition AS mpc --  Select table generated by CTE minutes_played_condition (5)
    JOIN ucl21_22.goalkeeping AS gk ON mpc.id_player = gk.id_player -- Join defending table according to id_player (8)
    JOIN ucl21_22.disciplinary AS disc ON mpc.id_player = disc.id_player-- Join disciplinary table according to id_player (9)
        -- in WHERE, are defined the conditions applied to data (11)
    WHERE disc.red <2  -- No red cards
		AND disc.yellow <= 2  -- Up to 4 yellow cards
		AND gk.conceded<=10 -- At least one g4 balls recoverd or attempts
        AND gk.saved >10 -- At least 4 tackles won
)

-- Final query to select players who meet the conditions
SELECT	player_name, -- columns to get (13)
		position, 
        minutes_played, 
        yellow, 
        red, 
        conceded,
        saved
FROM goalkeeper_condition -- From fordward_condition table (12)
WHERE position = 'Goalkeeper' -- condition to select fordwards only (14)
ORDER BY player_name; -- sort data by player name(15)